backend:
  name: github
  repo: mdehollander/netlify-cms-test
  branch: master

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: content/blog
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
